[build]
  command = "npm install --legacy-peer-deps && NEXT_SKIP_TYPECHECKING=true npm run build"
  publish = ".next"
  
[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
